server:
  port: ${PORT:31001}
spring:
  application:
    name: nm‐service‐manage‐cms
  data:
    mongodb:
      uri: mongodb://localhost:27017/nm_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
    instance:
      prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
      ip-address: ${IP_ADDRESS:127.0.0.1}
      instance-id: ${spring.application.name}:${server.port} #指定实例id